[package]
name = "hawkeye"
version = "0.1.0"
authors = ["Roderick Bovee <roderick@onecodex.com>"]

[dependencies]
murmurhash3 = "0.0.5"
needletail = { version = "~0.1.0", git = "https://github.com/bovee/needletail" }
