[package]
name = "finch"
version = "0.1.0"
authors = ["Roderick Bovee & One Codex <roderick@onecodex.com>"]

[dependencies]
clap = "~2.19.0"
murmurhash3 = "~0.0.5"
needletail = "~0.1.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[profile.release]
debug = true
