[package]
name = "finch"
version = "0.1.0"
authors = ["Roderick Bovee <roderick@onecodex.com>"]

[dependencies]
clap = "~2.19.0"
murmurhash3 = "~0.0.5"
needletail = { version="~0.1.0", git="https://github.com/onecodex/needletail", rev="28cdf2903eb728c65fe7a6cb8ab6396f6aad0022" }
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[profile.release]
debug = true
